//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.31 at 02:14:41 PM EET 
//

package ua.nure.honcharenkoilchishen.entity.faculty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="faculty" type="{http://nure.ua/honcharenkoilchishen/faculty}Faculty" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "faculty"
})
@XmlRootElement(name = "faculties")
public class Faculties {

    protected List<Faculty> faculty;

    public Faculties() {
        this.faculty = new ArrayList<>();
    }

    public List<Faculty> getFaculty() {
        if (faculty == null) {
            faculty = new ArrayList<Faculty>();
        }
        return this.faculty;
    }

    public void setFaculty(List<Faculty> faculty) {
        this.faculty = faculty;
    }

    public void addFaculty(Faculty faculty) {
        this.faculty.add(faculty);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Faculties faculties = (Faculties) o;
        return Objects.equals(faculty, faculties.faculty);
    }

    @Override
    public int hashCode() {
        return Objects.hash(faculty);
    }

    @Override
    public String
    toString() {
        return "Faculties{" +
                "faculty=" + faculty +
                '}';
    }
}
