//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.31 at 02:14:41 PM EET 
//


package ua.nure.honcharenkoilchishen.entity.faculty;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for facultyBranch.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="facultyBranch">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Mathmetical"/>
 *     &lt;enumeration value="Philology"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "facultyBranch")
@XmlEnum
public enum FacultyBranch {

    @XmlEnumValue("Mathmetical")
    MATHMETICAL("Mathmetical"),
    @XmlEnumValue("Philology")
    PHILOLOGY("Philology");
    private final String value;

    FacultyBranch(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FacultyBranch fromValue(String v) {
        for (FacultyBranch c: FacultyBranch.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    @Override
    public String toString() {
        return "FacultyBranch{" +
                "value='" + value + '\'' +
                '}';
    }}

