//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.31 at 02:14:41 PM EET 
//


package ua.nure.honcharenkoilchishen.entity.faculty;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ua.nure.honcharenkoilchishen.entity.faculty package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.nure.honcharenkoilchishen.entity.faculty
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Faculty }
     * 
     */
    public Faculty createFaculty() {
        return new Faculty();
    }

    /**
     * Create an instance of {@link Faculty.Additional }
     * 
     */
    public Faculty.Additional createFacultyAdditional() {
        return new Faculty.Additional();
    }

    /**
     * Create an instance of {@link Faculties }
     * 
     */
    public Faculties createFaculties() {
        return new Faculties();
    }

    /**
     * Create an instance of {@link Faculty.FacultyRoomNumber }
     * 
     */
    public Faculty.FacultyRoomNumber createFacultyFacultyRoomNumber() {
        return new Faculty.FacultyRoomNumber();
    }

    /**
     * Create an instance of {@link Faculty.Additional.BacheloerCount }
     * 
     */
    public Faculty.Additional.BacheloerCount createFacultyAdditionalBacheloerCount() {
        return new Faculty.Additional.BacheloerCount();
    }

}
